const Map<String, String> ar = {
  'login': 'تسجيل الدخول',
  'logout': 'تسجيل الخروج',
  'Main Menu': 'القائمة الرئيسية',
  'Add Child': 'إضافة طفل',
  'Coming Events': 'الاحداث القادمة',
  'Change Language': 'تغير اللغة',
  'Not Found Data': 'لا توجد بيانات',
  'Children': 'الابناء',
  'View The Daily Report': 'عرض التقرير اليومى',
  'Perform of': 'اداء',
  'Today': 'اليوم',
  'Your child is not registered to subscribe now':
      'طفلك غير مسجل باشتراك   اشترك الان',
  'Share': 'مشاركة',
  'Class': 'الفصل',
  'Report': 'التقرير',
  'ُEstimate': 'التقييم',
  'Activity': 'النشاط',
  'General': 'عام',
  'language development': 'النمو اللغوي',
  'Learn new crafts': 'يتعرف علي الحرف الجديد',
  'Distinguish the shape of the letter': 'يميز شكل الحرف',
  'Distinguish the sound of the letter': 'يميز صوت الحرف',
  'Able to write letters': 'متمكن من كتابة الحرف',
  'Cognitive pillars': 'الأركان الادراكية',
  'Enjoy and immerse with Pillars': 'يستمتع و يندمج بالاركان',
  'Mastering the activity (Montessori)': 'يتقن النشاط ( المنتسوري ) ',
  'Returns toys and tools after completing them':
      'يعيد الالعاب والادوات بعد الانتهاء منها',
  'Artistic activity': 'النشاط الفني',
  'Merges into the Artistic side': 'يندمج في الركن الفني',
  'Depends on himself in the Artistic side': 'يعتمد علي نفسه في الركن الفني',
  'The Story': 'القصة',
  'Enjoys hearing the story': 'يستمتع بسماع القصة',
  'Morning physical activity': 'النشاط الحركي الصباحي',
  'Enjoying the morning activity': 'يستمتع بالنشاط الصباحى',
  'Likes to share with friends': 'يحب المشاركة مع الإصدقاء',
  'the Party': 'الحلقة',
  'Say hello to peace and return peace': 'يلقي تحية السلام و يرد السلام',
  'Enjoy and take part in the party': 'يستمتع بالحلقة و يشارك فيها',
  'He sings the chant of unity': 'يردد انشودة الوحدة',
  'The Holy Quran': 'القران الكريم',
  'enjoy and listen': 'يستمتع و ينصت',
  'repeating the verses': 'يردد الايات',
  'Child Mood': 'مزاج الطفل',
  'morning': 'الصباح',
  'noon': 'الظهر',
  'afternoon time': 'العصر',
  'eat': 'الاكل',
  'the breakfast': 'الافطار',
  'the lunch': 'الغداء',
  'Snack': 'وجبة خفيفة',
  'Drinks': 'المشروبات',
  'water': 'المياه',
  'the milk': 'الحليب',
  'The sleep': 'النوم',
  'nap': 'القيلولة',
  'The Temperature': 'الحرارة',
  'Select Data': 'اختيار التاريخ',
  'A.m': 'صباحا',
  'Please bring a order of your choice': 'يرجي احضار طلب علي اختيارك',
  'Choose your business location or your residence location':
      'اختر موقع عملك او موقع السكن الخاص بك',
  'Select your location': 'حدد موقعك',
  'Something went wrong': 'حدث خطأ ما',
  'Branch must be selected': 'يجب اختيار الفرع',
  'Choose the branch closest to you': 'اختر الفرع الاقرب لك',
  'Next': 'التالى',
  'Gregorian': 'ميلادى',
  'Hijri ': 'هجرى',
  'birth date ': 'تاريخ الميلاد',
  'male': 'ولد',
  'female': 'بنت',
  'Gender': 'النوع',
  'Please make sure to choose your date of birth':
      'يرجى التأكد من اختيار تاريخ الميلاد',
  'Please make sure you choose the class and teacher':
      'يرجى التأكد من اختيار الفصل و المعلم',
  'Please make sure to choose your age group and gender':
      'يرجى التأكد من اختيار الفئة العمرية والنوع',
  'Please make sure to choose photos': 'يرجى التأكد من اختيار الصور',
  'Child Data': 'بيانات الطفل',
  'Teachers': 'المعلمين',
  'Please enter a valid value': 'من فضلك ادخل قيمة صحيحة',
  'Name': 'الاسم',
  'Anthor Notes': 'ملاحظات اخرى',
  'First Parent': 'ولى الامر الاول',
  'First Name': 'الاسم الاول',
  'Second Name': 'الاسم الثانى',
  'Family Name': 'اسم العائلة',
  'relative relation': 'صلة القرابة',
  'The email is invalid': 'البريد الالكترونى غير صالح',
  'Email': 'البريد الالكترونى ',
  'Phone Number': 'رقم الجوال',
  'The second Parent': 'ولى الامر الثانى',
  'Family Card': 'بطاقة العائلة',
  'Attach a photo of the family card': 'ارفق صورة بطاقة العائلة',
  'Vaccination certificates': 'شهادات التطعيمات',
  'Attach of the vaccination certificates': 'ارفق صورة شهادات التطعيمات',
  'Child picture': 'صورة الطفل',
  'Attach a picture of the child': 'ارفق صورة الطفل',
  'Does the child have an allergy?': 'هل يعانى الطفل من حساسية',
  'Please tell us what type of allergy your child has':
      'فضلا اخبرنا نوع الحساسية الخاصة بطفلك',
  'I want my baby to be photographed': 'اقبل ان يتم تصوير طفلى',
  'To post on social media': 'للنشر على وسائل التواصل الاجتماعى',
  'for emergency': 'للطوارئ',
  'emergency number': 'رقم الطوارئ',
  'payment': 'الدفع',
  'From 2 to 7': 'من 2 الى 7',
  'From 5 to 7': 'من 5 الى 7',
  'Please choose the subscription value': 'يرجى اختيار قيمة الاشتراك',
  'Please choose the payment method': 'يرجى اختيار طريقة الدفع',
  'Choose the period :': 'اختر الفترة  : ',
  'Pill :': 'الفاتورة',
  'Price :': 'السعر',
  'Tax :': 'الضريبة',
  'Rial': 'ريال',
  'Total :': 'الاجمالى',
  'Requirments for Payment': 'متطلبات الفاتورة',
  'street': 'الشارع',
  'city': 'المدينة',
  'district': 'المقاطعة',
  'Confirm': 'التأكيد',
  'By registering, you agree to the terms and conditions':
      'بالتسجيل فانت توافق علي الشروط و الاحكام',
  'Postal code': 'الرمز البريدي',
  'Payment completed successfully': 'تم الدفع بنجاح',
  'Payment in progress...': 'جارى إتمام الدفع...',
  'Payment Failed': 'فشل فى عملية الدفع',
  'Operation code...': 'كود العملية...',
  'try again': 'المحاولة من جديد',
  'Back to main menu': 'العودة للقائمة الرئسية',
  'Please try again': 'من فضلك حاول مرة اخرى',
  'Login': 'دخول',
  'Password': 'كلمة المرور',
  'You do not have an account, register here':
      'ليس لديك حساب ، قم بالتسجيل من هنا',
  'notifications': 'الاشعارات',
  'Register': 'التسجيل',
  'Personal Data': 'البيانات الشخصية',
  'Check it now': 'قم بفحصه الان',
  'Account created successfully': 'تم إنشاء حساب بنجاح',
  'Your child has been successfully added': 'تم اضافة طفلك بنجاح',
};
