const Map<String, String> en = {
  'login': 'login',
  'logout': 'logout',
  'Main Menu': 'Main Menu',
  'Add Child': 'Add Child',
  'Coming Events': 'Coming Events',
  'Change Language': 'Change Language',
  'Not Found Data': 'Not Found Data',
  'Children': 'Children',
  'View The Daily Report': 'View The Daily Report',
  'Perform of': 'Perform of',
  'Today': 'Today',
  'Your child is not registered to subscribe now':
      'Your child is not registered to subscribe now',
  'Share': 'Share',
  'Class': 'Class',
  'Report': 'Report',
  'ُEstimate': 'ُEstimate',
  'Activity': 'Activity',
  'General': 'General',
  'language development': 'language development',
  'Learn new crafts': 'Learn new crafts',
  'Distinguish the shape of the letter': 'Distinguish the shape of the letter',
  'Distinguish the sound of the letter': 'Distinguish the sound of the letter',
  'Able to write letters': 'Able to write letters',
  'Cognitive pillars': 'Cognitive pillars',
  'Enjoy and immerse with Pillars': 'Enjoy and immerse with Pillars',
  'Mastering the activity (Montessori)': 'Mastering the activity (Montessori)',
  'Returns toys and tools after completing them':
      'Returns toys and tools after completing them',
  'Artistic activity': 'Artistic activity',
  'Merges into the Artistic side': 'Merges into the Artistic side',
  'Depends on himself in the Artistic side':
      'Depends on himself in the Artistic side',
  'The Story': 'The Story',
  'Enjoys hearing the story': 'Enjoys hearing the story',
  'Morning physical activity': 'Morning physical activity',
  'Enjoying the morning activity': 'Enjoying the morning activity',
  'Likes to share with friends': 'Likes to share with friends',
  'the Party': 'the Party',
  'Say hello to peace and return peace': 'Say hello to peace and return peace',
  'Enjoy and take part in the party': 'Enjoy and take part in the party',
  'He sings the chant of unity': 'He sings the chant of unity',
  'The Holy Quran': 'The Holy Quran',
  'enjoy and listen': 'enjoy and listen',
  'repeating the verses': 'repeating the verses',
  'Child Mood': 'Child Mood',
  'morning': 'morning',
  'noon': 'noon',
  'afternoon time': 'afternoon time',
  'eat': 'eat',
  'the breakfast': 'the breakfast',
  'the lunch': 'the lunch',
  'Snack': 'Snack',
  'Drinks': 'Drinks',
  'water': 'water',
  'the milk': 'the milk',
  'The sleep': 'The sleep',
  'nap': 'nap',
  'The Temperature': 'The Temperature',
  'Select Data': 'Select Data',
  'A.m': 'A.m',
  'Please bring a order of your choice': 'Please bring a order of your choice',
  'Choose your business location or your residence location':
      'Choose your business location or your residence location',
  'Select your location': 'Select your location',
  'Something went wrong': 'Something went wrong',
  'Branch must be selected': 'Branch must be selected',
  'Choose the branch closest to you': 'Choose the branch closest to you',
  'Next': 'Next',
  'Gregorian': 'Gregorian',
  'Hijri ': 'Hijri',
  'birth date ': 'birth date',
  'male': 'male',
  'female': 'female',
  'Gender': 'Gender',
  'Please make sure to choose your date of birth':
      'Please make sure to choose your date of birth',
  'Please make sure you choose the class and teacher':
      'Please make sure you choose the class and teacher',
  'Please make sure to choose your age group and gender':
      'Please make sure to choose your age group and gender',
  'Please make sure to choose photos': 'Please make sure to choose photos',
  'Child Data': 'Baby Data',
  'Teachers': 'Teachers',
  'Please enter a valid value': 'Please enter a valid value',
  'Name': 'Name',
  'Anthor Notes': 'Anthor Notes',
  'First Parent': 'First Parent',
  'First Name': 'First Name',
  'Second Name': 'Second Name',
  'Family Name': 'Family Name',
  'relative relation': 'relative relation',
  'The email is invalid': 'The email is invalid',
  'Email': 'Email',
  'Phone Number': 'Phone Number',
  'The second Parent': 'The second Parent',
  'Family Card': 'Family Card',
  'Attach a photo of the family card': 'Attach a photo of the family card',
  'Vaccination certificates': 'Vaccination certificates',
  'Attach of the vaccination certificates':
      'Attach of the vaccination certificates',
  'Child picture': 'Child picture',
  'Attach a picture of the child': 'Attach a picture of the child',
  'Does the child have an allergy?': 'Does the child have an allergy?',
  'Please tell us what type of allergy your child has':
      'Please tell us what type of allergy your child has',
  'I want my baby to be photographed': 'I want my baby to be photographed',
  'To post on social media': 'To post on social media',
  'for emergency': 'for emergency',
  'emergency number': 'emergency number',
  'payment': 'payment',
  'From 2 to 7': 'From 2 to 7',
  'From 5 to 7': 'From 5 to 7',
  'Please choose the subscription value':
      'Please choose the subscription value',
  'Choose the period :': 'Choose the period :',
  'Pill :': 'Pill',
  'Price :': 'Price',
  'Tax :': 'Tax',
  'Rial': 'Rial',
  'Total :': 'Total',
  'Requirments for Payment': 'Requirments for Payment',
  'street': 'street',
  'city': 'city',
  'district': 'district',
  'Confirm': 'Confirm',
  'Please choose the payment method': 'Please choose the payment method',
  'By registering, you agree to the terms and conditions':
      'By registering, you agree to the terms and conditions',
  'Postal code': 'Postal code',
  'Payment completed successfully': 'Payment completed successfully',
  'Payment in progress...': 'Payment in progress...',
  'Payment Failed': 'Payment Failed',
  'Operation code...': 'Operation code...',
  'try again': 'try again',
  'Back to main menu': 'Back to main menu',
  'Please try again': 'Please try again',
  'Login': 'Login',
  'Password': 'Password',
  'You do not have an account, register here':
      'You do not have an account, register here',
  'notifications': 'notifications',
  'Register': 'Register',
  'Personal Data': 'Personal Data',
  'Check it now': 'Check it now',
  'Account created successfully': 'Account created successfully',
  'Your child has been successfully added':
      'Your child has been successfully added',
};
